"""empty message

Revision ID: 2b91fb0d4d14
Revises: e84decb7ff45
Create Date: 2015-12-20 22:49:06.148068

"""

# revision identifiers, used by Alembic.
revision = '2b91fb0d4d14'
down_revision = 'e84decb7ff45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_name_en'), 'stations', ['name_en'], unique=False)
    op.create_index(op.f('ix_stations_name_ru'), 'stations', ['name_ru'], unique=False)
    op.create_index(op.f('ix_stations_name_ua'), 'stations', ['name_ua'], unique=False)
    op.create_index(op.f('ix_stations_station_id'), 'stations', ['station_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_station_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_name_ua'), table_name='stations')
    op.drop_index(op.f('ix_stations_name_ru'), table_name='stations')
    op.drop_index(op.f('ix_stations_name_en'), table_name='stations')
    op.drop_table('requests')
    ### end Alembic commands ###
