"""empty message

Revision ID: e84decb7ff45
Revises: None
Create Date: 2015-12-17 23:02:56.363880

"""

# revision identifiers, used by Alembic.
revision = 'e84decb7ff45'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_ua', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    ### end Alembic commands ###
